### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/tenant-security-client-java#19]
As an IronCore dev wanting to release tenant-security-client-java
I want clear instructions and a working release commands

I was using the following mvn and java versions on Kubuntu 20.04
```
clintf@carbon2:~/workspace/tenant-security-client-java$ mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.8, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-42-generic", arch: "amd64", family: "unix"
clintf@carbon2:~/workspace/tenant-security-client-java$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
clintf@carbon2:~/workspace/tenant-security-client-java$ 
```

The command `mvn clean source:jar javadoc:jar deploy` did not succeed. First complaining about javadoc, then failing to run the tests. I was able to resolve the javadoc issue by upgrading some of the maven plugins and introducing a specific plugin to do javadoc builds.

In addition to creating the release, we should document any other assumptions about sonatype credentials, changelogs, and pre/post release testing.

**Comment by BobWall23** [comment]
Make sure to update the README with any constraints (Java version, etc.)
